#!/usr/bin/env bash
# setup-hooks.sh — richtet prek-Hooks in einem Repo ein (Python und/oder R).
#
# Aufruf, Flags und Exit-Codes: usage() unten bzw. --help.
#
# Herkunft: Forge-Durchgang 09.09.2026, Rohmaterial https://prek.j178.dev/
# Entscheidungen: air statt styler (Formatierung ohne R-Runtime), lintr
# zusaetzlich (braucht System-R), ruff + ty auf der Python-Seite.
#
# Closed loop:
#   Messung:   Existiert .git/hooks/pre-commit in den Repos, und meldet prek
#              beim Commit reale Funde ("files were modified by this hook")?
#   Latenz:    sofort, bei jedem Commit.
#   Kriterium: nach 4 Wochen in >=2 Repos aktiv, mindestens 1 realer Fund.
#   Anpassung: kein Fund -> Hookset kuerzen. Skript nie ein zweites Mal
#              benutzt -> auf reine Templates zurueckstufen. lintr zu langsam
#              -> stages: [pre-push].
#   Review:    07.10.2026

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FRAGMENTS="${SCRIPT_DIR}/fragments"
BASE="base-compat.yaml"
FORCE=0

usage() {
  cat <<'EOF'
Usage: setup-hooks.sh [--builtin] [--force]
Assembles .pre-commit-config.yaml from fragments/ for the detected project
type (Python and/or R), then runs `prek update --cooldown-days 7` and
`prek install`. Run from anywhere inside the target Git repo.
  --builtin   generic hooks as prek builtins (no clone, no Python env; prek-only)
  --force     overwrite an existing .pre-commit-config.yaml / prek.toml
  -h, --help  this text
Examples:
  setup-hooks.sh
  setup-hooks.sh --builtin --force
Exit codes:
  0  config written and hooks installed
  2  unknown argument
  3  environment: fragments missing, not a Git repo, or prek not on PATH
  4  .pre-commit-config.yaml or prek.toml already exists (use --force)
  5  neither Python nor R detected
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --builtin) BASE="base-builtin.yaml"; shift ;;
    --force)   FORCE=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1 (see --help)" >&2; exit 2 ;;
  esac
done

[[ -d "$FRAGMENTS" ]] || { echo "Fragments not found: $FRAGMENTS" >&2; exit 3; }

ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" || {
  echo "Not a Git repository." >&2; exit 3; }
cd "$ROOT"

command -v prek >/dev/null 2>&1 || {
  echo "prek not on PATH. Install e.g.: uv tool install prek" >&2; exit 3; }

CONFIG=".pre-commit-config.yaml"
if [[ -e "$CONFIG" && $FORCE -eq 0 ]]; then
  echo "$CONFIG already exists. Overwrite with --force." >&2; exit 4
fi
if [[ -e "prek.toml" && $FORCE -eq 0 ]]; then
  echo "prek.toml already exists; prek would ignore the YAML. Overwrite with --force." >&2; exit 4
fi

has_python=0
has_r=0
[[ -f pyproject.toml || -f setup.py ]] && has_python=1
[[ -n "$(git ls-files -- '*.py' | head -n1)" ]] && has_python=1
[[ -f DESCRIPTION ]] && has_r=1
[[ -n "$(git ls-files -- '*.R' '*.r' | head -n1)" ]] && has_r=1

if [[ $has_python -eq 0 && $has_r -eq 0 ]]; then
  echo "Neither Python nor R files found. Nothing to set up." >&2; exit 5
fi

if [[ $has_r -eq 1 ]] && ! command -v Rscript >/dev/null 2>&1; then
  echo "WARNING: Rscript missing; the lintr hook will fail at run time." >&2
fi

# ruff >= 0.16 aktiviert 413 statt 59 Default-Regeln. Ohne eigene
# Regelauswahl flutet der erste Lauf das Repo mit Funden.
if [[ $has_python -eq 1 && ! -e ruff.toml && ! -e .ruff.toml ]] \
  && ! grep -qs '^\[tool\.ruff' pyproject.toml; then
  echo "WARNING: no ruff config found; ruff >= 0.16 enables 413 rules by default." >&2
  echo '         Pin e.g. [tool.ruff.lint] select = ["E", "F", "I", "B", "UP"] in pyproject.toml.' >&2
fi

{
  echo "# Generated by setup-hooks.sh on $(date +%F). Runner: prek."
  echo "# Update revs with 'prek update --cooldown-days 7'."
  cat "${FRAGMENTS}/${BASE}"
  [[ $has_python -eq 1 ]] && cat "${FRAGMENTS}/python.yaml"
  [[ $has_r -eq 1 ]] && cat "${FRAGMENTS}/r.yaml"
} > "$CONFIG"

echo "Written: ${ROOT}/${CONFIG} (python=${has_python}, r=${has_r}, base=${BASE})"

if ! prek update --cooldown-days 7; then
  echo "WARNING: 'prek update' failed; revs stay at the fragment pins" >&2
  echo "         and may be outdated." >&2
fi

prek install

cat <<'EOF'

Next step, deliberately not run automatically:

  prek run --all-files

The first run reformats the whole repo and produces a large diff.
Commit it on its own, not together with the next feature change.
EOF
